matrix:
  include:

  - env:
      - NAME="Python 2.7, Qt 5.6"
      - PYSIDE_BRANCH=5.6
      - QT_VER=5.6.3
      - BREW_PY="python"
      - CI_PY=/usr/local/bin/python2
      - CI_CMAKE=/usr/local/bin/cmake
      - CI_QMAKE=${HOME}/Qt-${QT_VER}/${QT_VER}/clang_64/bin/qmake
      - QT_INSTALLER_FILE=qt-opensource-mac-x64-clang-${QT_VER}
      - QT_INSTALL_PATH=${HOME}/Qt-${QT_VER}
    os: osx
    osx_image: xcode6.4
    language: generic
    # cache:
    #   timeout: 2000
    #   directories:
    #     - ${QT_INSTALL_PATH}

  - env:
      - NAME="Python 3.5, Qt 5.6"
      - PYSIDE_BRANCH=5.6
      - QT_VER=5.6.3
      - BREW_PY=https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb
      - CI_PY=/usr/local/bin/python3
      - CI_CMAKE=/usr/local/bin/cmake
      - CI_QMAKE=${HOME}/Qt-${QT_VER}/${QT_VER}/clang_64/bin/qmake
      - QT_INSTALLER_FILE=qt-opensource-mac-x64-clang-${QT_VER}
      - QT_INSTALL_PATH=${HOME}/Qt-${QT_VER}
    os: osx
    osx_image: xcode6.4
    language: generic
    # cache:
    #   timeout: 2000
    #   directories:
    #     - ${QT_INSTALL_PATH}

  - env:
      - NAME="Python 3.6, Qt 5.6"
      - PYSIDE_BRANCH=5.6
      - QT_VER=5.6.3
      - BREW_PY=https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/python3.rb
      - CI_PY=/usr/local/bin/python3
      - CI_CMAKE=/usr/local/bin/cmake
      - CI_QMAKE=${HOME}/Qt-${QT_VER}/${QT_VER}/clang_64/bin/qmake
      - QT_INSTALLER_FILE=qt-opensource-mac-x64-clang-${QT_VER}
      - QT_INSTALL_PATH=${HOME}/Qt-${QT_VER}
    os: osx
    osx_image: xcode6.4
    language: generic
    # cache:
    #   timeout: 2000
    #   directories:
    #     - ${QT_INSTALL_PATH}

  - env:
      - NAME="Python 2.7, Qt 5.9"
      - PYSIDE_BRANCH=5.9
      - QT_VER=5.9.4
      - BREW_PY=""
      - CI_PY=/usr/local/bin/python2
      - CI_CMAKE=/usr/local/bin/cmake
      - CI_QMAKE=${HOME}/Qt-${QT_VER}/${QT_VER}/clang_64/bin/qmake
      - LIBCLANG_FILE=libclang-release_50-mac.7z
      - QT_INSTALLER_FILE=qt-opensource-mac-x64-${QT_VER}
      - QT_INSTALL_PATH=${HOME}/Qt-${QT_VER}
    os: osx
    osx_image: xcode8.3
    language: generic
    # cache:
    #   timeout: 2000
    #   directories:
    #     - ${QT_INSTALL_PATH}

  - env:
      - NAME="Python 3.5, Qt 5.9"
      - PYSIDE_BRANCH=5.9
      - QT_VER=5.9.4
      - BREW_PY=https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb
      - CI_PY=/usr/local/bin/python3
      - CI_CMAKE=/usr/local/bin/cmake
      - CI_QMAKE=${HOME}/Qt-${QT_VER}/${QT_VER}/clang_64/bin/qmake
      - LIBCLANG_FILE=libclang-release_50-mac.7z
      - QT_INSTALLER_FILE=qt-opensource-mac-x64-${QT_VER}
      - QT_INSTALL_PATH=${HOME}/Qt-${QT_VER}
    os: osx
    osx_image: xcode8.3
    language: generic
    # cache:
    #   timeout: 2000
    #   directories:
    #     - ${QT_INSTALL_PATH}

  - env:
      - NAME="Python 3.6, Qt 5.9"
      - PYSIDE_BRANCH=5.9
      - QT_VER=5.9.4
      - BREW_PY=https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/python3.rb
      - CI_PY=/usr/local/bin/python3
      - CI_CMAKE=/usr/local/bin/cmake
      - CI_QMAKE=${HOME}/Qt-${QT_VER}/${QT_VER}/clang_64/bin/qmake
      - LIBCLANG_FILE=libclang-release_50-mac.7z
      - QT_INSTALLER_FILE=qt-opensource-mac-x64-${QT_VER}
      - QT_INSTALL_PATH=${HOME}/Qt-${QT_VER}
    os: osx
    osx_image: xcode8.3
    language: generic
    # cache:
    #   timeout: 2000
    #   directories:
    #     - ${QT_INSTALL_PATH}


before_install:
  - pwd
  - ls -alh ${HOME}
  - ls /usr/local/bin
  - ls /usr/local/Cellar
  - sw_vers -productVersion
  - /usr/bin/xcodebuild -version


install:
  # Fix issue on xcode6.4: https://github.com/Homebrew/brew/issues/3299#issuecomment-335837083
  - brew update

  # Python
  - if [ "$BREW_PY" != "" ]; then brew install ${BREW_PY} ; fi

  # pip
  - ${CI_PY} -m pip install --user --upgrade pip setuptools wheel

  # lxml
  - brew install libxslt libxml2

  # 7zip
  - brew install tree p7zip

  # Qt
  - if [ ! -d "${QT_INSTALL_PATH}" ] ; then curl -L -O https://download.qt.io/archive/qt/${PYSIDE_BRANCH}/${QT_VER}/${QT_INSTALLER_FILE}.dmg ; fi
  - if [ ! -d "${QT_INSTALL_PATH}" ] ; then hdiutil attach -noverify ${QT_INSTALLER_FILE}.dmg ; fi
  - if [ ! -d "${QT_INSTALL_PATH}" ] ; then travis_wait 15 /Volumes/${QT_INSTALLER_FILE}/${QT_INSTALLER_FILE}.app/Contents/MacOS/${QT_INSTALLER_FILE} --script qt-installer-${QT_VER}-noninteractive.qs -platform minimal ; fi
  - if [ -d "/Volumes/${QT_INSTALLER_FILE}" ] ; then hdiutil detach /Volumes/${QT_INSTALLER_FILE} ; fi
  - rm -rf ${QT_INSTALLER_FILE}.dmg

  # Debug
  - ls -alh /Users/travis/
  - ls -alh ${QT_INSTALL_PATH}
  - ls -alh ${QT_INSTALL_PATH}/${QT_VER}
  - ls -alh ${QT_INSTALL_PATH}/${QT_VER}/clang_64
  - ls -alh ${QT_INSTALL_PATH}/${QT_VER}/clang_64/bin

  # libclang
  - if [ "$PYSIDE_BRANCH" == "5.9" ]; then curl -L -O http://download.qt.io/development_releases/prebuilt/libclang/${LIBCLANG_FILE} ; fi
  - if [ "$PYSIDE_BRANCH" == "5.9" ]; then 7z x ${LIBCLANG_FILE} ; fi
  - if [ "$PYSIDE_BRANCH" == "5.9" ]; then export CLANG_INSTALL_DIR=$(pwd)/libclang ; fi
  - if [ "$PYSIDE_BRANCH" == "5.9" ]; then rm -rf ${LIBCLANG_FILE} ; fi


  # CMake 3.x already provided by Travis CI
  # - brew install cmake

  - git clone --recursive --branch ${PYSIDE_BRANCH} https://code.qt.io/pyside/pyside-setup.git pyside-setup


before_script:
  # Show which commit is being used
  - git --git-dir pyside-setup/.git log -n 1

  # Summary
  - ${CI_PY} --version
  - ${CI_CMAKE} --version
  - ${CI_QMAKE} --version
  - git --version
  - clang --version
  - sw_vers -productVersion
  - /usr/bin/xcodebuild -version
  - df -h
  - ls /usr/local/Cellar


script:
  - ${CI_PY} pyside-setup/setup.py bdist_wheel --ignore-git --standalone --no-examples --qmake=${CI_QMAKE} --cmake=${CI_CMAKE} --jobs=3
  - ls -alh pyside-setup/dist


# before_cache:
#   - echo "About to perform caching of Qt installation dir..."


# after_success:
#   - ls -alh


# after_failure:
#   - ls -alh


# before_deploy:
#   - ...


deploy:
  provider: releases
  api_key:
    secure: UpN7G0GHDL+pbNdxnwYQuQO8hlkJUqk2xYvSioHJHCSi/BP8Xihsnw40ohhbJTnm2q1d38vreee/MvaDCKBnJ53rsBRa3FUUHDudGlPiu9/v0mkBvu18waOdsH4njUSP3vnKU+HRDB1Mha1CtksyQU6G0SGKg96YjSqAQa+9hi0XxtDRzedekSQZWv8MiXObz7aLNvtJBib66Od3KcEsboiHI4LIKHywPyXUOwO7XGQE7d4D+b0RjGKoZMLABY+kd5z+wzx93KRlI2Q+yUFxPkFWa1j4OWLyoC/oDCRahve3+rQQtt60W95bBLQrqVl+ptnyzav6nz3chgEZAvxGt07Cs+dCFT8qQtr+v44aqnOStoKadb0GHexTjb37oVnDheSrNcrnXc/u5ZlYNNnDU0xsE5O2al57peyiXOb6HwPiB1BQxBUj39BdPHZMzJc8iL0O8hx2fP5J2ysdvwpnYGB3Xy6gkeRSGlFjZHiMt+7nlPgqWYolvDvE20ITl6zMOonSsTWkS1+F3C/7eJNbQL6s0gEVj22/b4l2WSKKtukT8CGGmAhunEZL02XDnhm3SijPvHp+kA9xbWJ2aMkcueibOOkaUwqbY6Prvp1MYGLGLfpRr3A7EkzPZ2FCzuWq4DDtNR0nuBtrh8euMdYCUb+QCysoYkpt5i+hDQRS8SE=
  file_glob: true
  file: pyside-setup/dist/*.whl
  overwrite: true
  skip_cleanup: true
  on:
    repo: fredrikaverpil/pyside2-macos
    tags: true


# after_deploy:
# after_script:
